name: 設置 Python 環境和安裝依賴
description: '安裝 Python、uv 和專案依賴'
runs:
  using: "composite"
  steps:
    - name: 安裝 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: 安裝 uv 並建立虛擬環境
      shell: pwsh
      run: |
        pip install uv
        uv venv
    - name: 啟用 uv
      shell: pwsh
      run: |
        .\.venv\Scripts\Activate